PACKAGE_NAME="memwatcher"
PACKAGE_VERSION="1.0.0"
BUILT_MODULE_NAME[0]="memwatcher"
BUILT_MODULE_LOCATION[0]="kernel/"
DEST_MODULE_LOCATION[0]="/extra"
MAKE[0]="make KDIR=/lib/modules/${kernelver}/build module"
CLEAN="make KDIR=/lib/modules/${kernelver}/build clean"
AUTOINSTALL="yes"
